import { type NextPage } from "next";
import Head from "next/head";
import  {Header} from '~/components/Header';
import { api } from "~/utils/api";
import { useTheme } from "~/utils/themeContext";

const Home: NextPage = () => {
  const { theme } = useTheme();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-theme={theme}>
          <Header/>
          
      </main>
    </>
  );
};

export default Home;

