import { type NextPage } from "next";
import Head from "next/head";
import  {Header} from '~/components/Header';
import  {Document} from '~/components/openAiimage'
import { api } from "~/utils/api";
import { useTheme } from "~/utils/themeContext";
import { useSession } from "next-auth/react";
import { Else } from "~/components/Else";
const Home: NextPage = () => {
  const { data: session, status } = useSession();
  const { theme } = useTheme();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-theme={theme}>
          <Header/>
          {session && <Document/>}
          {/* <Document/> */}
          {!session && <Else/>}
      </main>
    </>
  );
};

export default Home;

